version: "3.8"

services:
  ansible:
    image: willhallonline/ansible
    container_name: ansible_runner
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - ~/.ssh/vockey.pem:/root/.ssh/vockey.pem
