---
- name: Configure Pokemon Game Server
  hosts: frontend_servers
  become: yes

  vars:
    game_dir: /home/ubuntu/pokeapi-game

  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install requests via apt
      apt:
        name: python3-requests
        state: present

    - name: Clone pokeapi-game repo
      git:
        repo: "https://github.com/innuli4ka/pokemonpart3.git"
        dest: "{{ game_dir }}"
        update: yes
        version: main

    - name: Add auto-run to bashrc for SSH logins WITH BACKEND IP
      lineinfile:
        path: /home/ubuntu/.bashrc
        line: 'if [ -n "$SSH_CONNECTION" ]; then export BACKEND_API_URL="http://{{ hostvars[inventory_hostname].backend_ip }}:5000"; cd ~/pokeapi-game/pokeapi-game && python3 ui.py; fi'
        insertafter: EOF

    - name: Add auto-run to bashrc for SSH logins
      lineinfile:
        path: /home/ubuntu/.bashrc
        line: 'if [ -n "$SSH_CONNECTION" ]; then cd ~/pokeapi-game && python3 ui.py; fi'
        insertafter: EOF

    - name: Ensure ubuntu owns the game folder
      file:
        path: "{{ game_dir }}"
        owner: ubuntu
        group: ubuntu
        recurse: yes
