---
- name: Configure Pokemon Game Server
  hosts: backend_servers
  become: yes

  vars:
    game_dir: /home/ubuntu/pokeapi-game

  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install Python 3, pip and git
      apt:
        name:
          - python3
          - python3-pip
          - git
        state: present

    - name: Clone pokeapi-game repo
      git:
        repo: "https://github.com/innuli4ka/pokemonpart3.git"
        dest: "{{ game_dir }}"
        update: yes
        version: main

    - name: Install Python requests module
      pip:
        name: requests
        executable: pip3

    - name: Add auto-run to bashrc for SSH logins
      lineinfile:
        path: /home/ubuntu/.bashrc
        line: 'if [ -n "$SSH_CONNECTION" ]; then cd ~/pokeapi-game && python3 ui.py; fi'
        insertafter: EOF

    - name: Ensure ubuntu owns the game folder
      file:
        path: "{{ game_dir }}"
        owner: ubuntu
        group: ubuntu
        recurse: yes
